// Mock data for standalone mode (before Fender-AI integration)
// This allows the website to display content without connecting to Fender-AI

import type { FenderDealer, FenderVehicle } from './fenderApi';

export const mockDealer: FenderDealer = {
  id: 'uptown-auto-sales',
  name: 'Uptown Auto Sales',
  phone: '706-295-9700',
  city: 'Rome',
  state: 'GA',
  address: 'Rome, GA 30161',
  zip_code: '30161',
  email: 'sales@uptownautosales.com',
  website_url: 'https://uptownautosales.com',
  logo_url: '', // Add logo URL when available
  primary_color: '#dc2626',
};

export const mockVehicles: FenderVehicle[] = [
  {
    id: '1',
    slug: '2018-honda-accord-lx',
    year: 2018,
    make: 'Honda',
    model: 'Accord',
    trim: 'LX',
    price: 18995,
    asking_price: 18995,
    mileage: 45000,
    color: 'White',
    exterior_color: 'White',
    interior_color: 'Gray',
    drivetrain: 'FWD',
    transmission: 'Automatic',
    fuel_type: 'Gasoline',
    body_style: 'Sedan',
    engine: '1.5L Turbo',
    description: 'Clean Honda Accord with low miles. Great fuel economy and reliable transportation.',
    primary_photo_url: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=800',
    photo_urls: [
      'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    vin: '1HGCV1F13JA123456',
    stock_number: 'UAS001',
    features: ['Bluetooth', 'Backup Camera', 'Cruise Control', 'Power Windows'],
    mpg: { city: 30, highway: 38 },
  },
  {
    id: '2',
    slug: '2019-toyota-camry-se',
    year: 2019,
    make: 'Toyota',
    model: 'Camry',
    trim: 'SE',
    price: 21995,
    asking_price: 21995,
    mileage: 32000,
    color: 'Silver',
    exterior_color: 'Silver',
    interior_color: 'Black',
    drivetrain: 'FWD',
    transmission: 'Automatic',
    fuel_type: 'Gasoline',
    body_style: 'Sedan',
    engine: '2.5L 4-Cylinder',
    description: 'Sporty Camry SE with low miles. One owner, clean history.',
    primary_photo_url: 'https://images.pexels.com/photos/1007410/pexels-photo-1007410.jpeg?auto=compress&cs=tinysrgb&w=800',
    photo_urls: [
      'https://images.pexels.com/photos/1007410/pexels-photo-1007410.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    vin: '4T1B11HK9KU123456',
    stock_number: 'UAS002',
    features: ['Sunroof', 'Leather Seats', 'Navigation', 'Blind Spot Monitor'],
    mpg: { city: 28, highway: 39 },
  },
  {
    id: '3',
    slug: '2017-ford-f150-xlt',
    year: 2017,
    make: 'Ford',
    model: 'F-150',
    trim: 'XLT',
    price: 28995,
    asking_price: 28995,
    mileage: 58000,
    color: 'Blue',
    exterior_color: 'Blue',
    interior_color: 'Gray',
    drivetrain: '4WD',
    transmission: 'Automatic',
    fuel_type: 'Gasoline',
    body_style: 'Truck',
    engine: '5.0L V8',
    description: 'Powerful F-150 with 4WD. Perfect for work or play. Clean title.',
    primary_photo_url: 'https://images.pexels.com/photos/1149137/pexels-photo-1149137.jpeg?auto=compress&cs=tinysrgb&w=800',
    photo_urls: [
      'https://images.pexels.com/photos/1149137/pexels-photo-1149137.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    vin: '1FTEW1EF5HFA12345',
    stock_number: 'UAS003',
    features: ['4WD', 'Tow Package', 'Running Boards', 'Bed Liner'],
    mpg: { city: 16, highway: 22 },
  },
  {
    id: '4',
    slug: '2020-nissan-altima-sv',
    year: 2020,
    make: 'Nissan',
    model: 'Altima',
    trim: 'SV',
    price: 19995,
    asking_price: 19995,
    mileage: 28000,
    color: 'Red',
    exterior_color: 'Red',
    interior_color: 'Black',
    drivetrain: 'FWD',
    transmission: 'Automatic',
    fuel_type: 'Gasoline',
    body_style: 'Sedan',
    engine: '2.5L 4-Cylinder',
    description: 'Like new Altima with advanced safety features. Great commuter car.',
    primary_photo_url: 'https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg?auto=compress&cs=tinysrgb&w=800',
    photo_urls: [
      'https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    vin: '1N4BL4DV6LC123456',
    stock_number: 'UAS004',
    features: ['Apple CarPlay', 'Android Auto', 'Lane Departure Warning', 'Automatic Emergency Braking'],
    mpg: { city: 28, highway: 39 },
  },
  {
    id: '5',
    slug: '2016-jeep-wrangler-sport',
    year: 2016,
    make: 'Jeep',
    model: 'Wrangler',
    trim: 'Sport',
    price: 24995,
    asking_price: 24995,
    mileage: 65000,
    color: 'Black',
    exterior_color: 'Black',
    interior_color: 'Black',
    drivetrain: '4WD',
    transmission: 'Manual',
    fuel_type: 'Gasoline',
    body_style: 'SUV',
    engine: '3.6L V6',
    description: 'Iconic Wrangler ready for adventure. Manual transmission, removable top.',
    primary_photo_url: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=800',
    photo_urls: [
      'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    vin: '1C4BJWDG3GL123456',
    stock_number: 'UAS005',
    features: ['4WD', 'Removable Top', 'Off-Road Tires', 'Winch'],
    mpg: { city: 17, highway: 21 },
  },
  {
    id: '6',
    slug: '2019-chevrolet-equinox-lt',
    year: 2019,
    make: 'Chevrolet',
    model: 'Equinox',
    trim: 'LT',
    price: 20995,
    asking_price: 20995,
    mileage: 42000,
    color: 'Gray',
    exterior_color: 'Gray',
    interior_color: 'Black',
    drivetrain: 'AWD',
    transmission: 'Automatic',
    fuel_type: 'Gasoline',
    body_style: 'SUV',
    engine: '1.5L Turbo',
    description: 'Compact SUV with AWD. Perfect for families or commuting.',
    primary_photo_url: 'https://images.pexels.com/photos/112451/pexels-photo-112451.jpeg?auto=compress&cs=tinysrgb&w=800',
    photo_urls: [
      'https://images.pexels.com/photos/112451/pexels-photo-112451.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    vin: '2GNAXUEV5K6123456',
    stock_number: 'UAS006',
    features: ['AWD', 'Backup Camera', 'Heated Seats', 'Remote Start'],
    mpg: { city: 26, highway: 32 },
  },
];

// Mock API responses
export const mockApi = {
  getDealer: (): Promise<FenderDealer> => {
    return Promise.resolve(mockDealer);
  },
  
  getInventory: () => {
    return Promise.resolve({
      vehicles: mockVehicles,
      pagination: {
        total: mockVehicles.length,
        page: 1,
        per_page: 20,
        total_pages: 1,
      },
    });
  },
  
  getVehicle: (id: string): Promise<FenderVehicle | undefined> => {
    return Promise.resolve(mockVehicles.find(v => v.id === id));
  },
  
  submitForm: (data: any) => {
    console.log('Mock form submission:', data);
    return Promise.resolve({ success: true, id: 'mock-' + Date.now() });
  },
};
